### PR TITLE
Add seller id and seller name to return request and show the informat…

### PR DESCRIPTION
**Pull request by claudiu-iviteb**
…ion in the request and admin pages

### CODE REVIEW

**Comment by claudiu-iviteb** [comment]
Hello @filafb . Sorry for missing all this info. The changes are for a client that wants to show seller information in a marketplace environment.
The workspace where it can be tested is here: https://claudiureturnapp--iviteb.myvtex.com/ . You can place orders, of course.

Also, using the sellerId that we capture in the request, we could set a trigger to notify him by email.

image

image

image

**Review by filafb — CHANGES_REQUESTED** [review]
Hey @claudiu-iviteb! All seems good. Can you just update the changelog file, please?

**Comment by filafb** [comment]
Hey @claudiu-iviteb, we had to do a couple of releases and your branch got outdated. Do you mind rebasing it, please?

**Comment by claudiu-iviteb** [comment]
@filafb Is it ok now?

**Review by filafb — APPROVED** [review]

**Comment by filafb** [comment]
> @filafb Is it ok now?
All good now. Thank you. We will just fix a bug on master so we can release a new version with it. Thanks.

**Pull request merged**
